config/routes.rb
OnlineStore::Application.routes.draw do

  root to: 'products#index'
  get '/signup', to:'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/basket', to: 'baskets#show'
  post '/basket', to: 'baskets#add'
  delete '/basket', to: 'baskets#destroy'

  resources :users
  resources :baskets, only: [:show, :add, :destroy]

end

app/models/basket.rb
class Basket
  include Mongoid::Document
  include Mongoid::Timestamps
  field :product_ids, type: Array, default: []

  belongs_to :user
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  field :product_id, type: Integer
  field :name, type: String
  field :price, type: Integer
  field :manufacturer, type: String
end

app/models/user.rb
class User
  include ActiveModel::SecurePassword
  include ActiveModel::Validations
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_one :basket

  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/ }
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true

  before_save { self.email = email.downcase }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include BasketsHelper
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def add
    basket = current_basket
    unless basket
      basket = Basket.new(user_id: current_user.id)
      basket.save
    end

    basket.product_ids << params[:product_id] if params[:product_id]

    respond_to do |format|
      if basket.save
        format.html { redirect_to products_path }
        format.js {}
      end
    end

  end

  def destroy
    basket = current_basket
    basket.product_ids = []

    respond_to do |format|
      if basket.save
        format.html { redirect_to '/basket' }
        format.js {}
      end
    end
  end

  def show
    @basket_products = basket_products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  	@products = Product.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login(user)
      redirect_to root_url
    else
      flash.now[:failure] = 'Invalid email\password.'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      login(@user)
      redirect_to root_url
    else
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper

  def current_basket_qty
    current_basket.product_ids.size
  end

  def current_basket
    @current_basket ||= Basket.find_by(user_id: current_user.id)
  end

  def basket_products
    return [] unless current_basket

    @basket_products = []
    current_basket.product_ids.each do |id|
      product = Product.find_by(product_id: id)
      @basket_products << product if product
    end

    @basket_products
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baskets/_empty.html.erb
<p>
  Your basket is empty.
  <%= link_to 'Go Back', root_path %> and add some products.
</p>

app/views/baskets/add.js.erb
$('#basket_qty')[0].textContent = <%= current_basket_qty %>

app/views/baskets/destroy.js.erb
$('#basket').empty();
$('#basket').html("<%= escape_javascript(render 'baskets/empty') %>")

app/views/baskets/show.html.erb
<h2>Basket</h2>

<div id='basket'>
  <% if basket_products.empty? %>
    <%= render 'baskets/empty' %>
  <% else %>
    <table class='table'>
    <% basket_products.each do |product| %>
    <tr>
      <td>
        <%= render 'products/product', product: product %>
      </td>
    </tr>
    <% end %>
    </table>
    <%= button_to 'Clear Basket', {controller: 'baskets', action: 'destroy'},
    method: :delete, data: {confirm: 'Are you sure?'}, remote: true %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<style type="text/css"></style>
</head>
<body>
  <h1>
  <%= link_to image_tag('rails.png'), root_url %>
  ONLINE STORE
  </h1>
  <hr />

<% flash.each do |message_type, message| %>
  <div class="notice-<%= message_type %>"><%= message %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/products/_product.html.erb
<div>
  <li>
    <strong><%= product.name %></strong>
  </li>
  <p>
  Price: <%= number_to_currency product.price %>
  Manufacturer: <%= product.manufacturer %>
  </p>
</div>

app/views/products/index.html.erb
<header>
  <div>
    <% if logged_in? %>
      <span>Welcome, </span>
      <%= current_user.name %>
      <span>|</span>
      <%= link_to 'Sign out', logout_path, method: :delete %>
      <span>|</span>
      <%= link_to 'Basket:', basket_path %>
      <span id='basket_qty'><%= current_basket_qty %></span>
    <% else %>
      <%= link_to 'Sign in', login_path %>
      <span>|</span>
      <%= link_to 'Sign up', signup_path %>
      <p class='notice-success'>Please Sign In to manage your basket.</p>
    <% end %>
  </div>
</header>

<h2>Products</h2>

<table class='table'>
<% @products.each do |product| %>
<tr>
  <td>
    <%= render 'products/product', product: product %>
  </td>
  <td>
  <% if logged_in? %>
    <%= button_to 'Add to Basket', {controller: 'baskets', action: 'add', product_id: product.product_id}, remote: true %>
  <% end %>
  </td>
</tr>
<% end %>
</table>

app/views/users/new.html.erb
<h2>Register New User</h2>
<div>
  <%= form_for(@user) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class='field'>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class='field'>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class='field'>
    <%= f.label :password_confirmation, 'Confirmation' %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  </div class='action'>
    <%= f.submit 'Create' %>
  </div>
  <% end %>
</div>